events {
	worker_connections 768;
}

http {
	server {
		listen 80;
		server_name localhost;

		# Static HTML
		location / {
			root /opt/myapp;
			index index.html;
		}

		# Backend API
		location /api/ {
			proxy_pass http://127.0.0.1:3000;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
		}
	}
}


